<?php
/**
 * Created by PhpStorm.
 * User: yhy
 * Date: 2019/10/9
 * Time: 16:21
 */

namespace app\admin\controller;


use think\Session;

class Main extends Base
{     public function _initialize()
{
    parent::_initialize(); // TODO: Change the autogenerated stub
}

    public function index(){
          $user=Session::get('user');
          return view('index',['user'=>$user]);
      }

}