<?php
/**
 * Created by PhpStorm.
 * User: yhy
 * Date: 2019/10/9
 * Time: 9:44
 */

namespace app\admin\controller;


use think\Controller;
use think\Db;

class Nav extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
        //查看
    }
    public function openinsert(){
        return view();
        //展示插入页面
    }
    public  function  insert(){
        //插入逻辑
        //验证请求的方式 参数
        $method=$this->request->method();
        if($method !='POST'){
            return json(['code'=>404,'msg'=>"插入失败"]);
        }
        $data=input('post.');
        $validata=validate('Nav');
       if(! $validata->scene('insert')->check($data)){
           return json(['code'=>404,'msg'=>$validata->getError()]);
       };




       $result= Db::table('nav')->insert($data);
        if($result>0){
           return json(['code'=>200,'msg'=>"插入成功"]);
        }else{
            return json(['code'=>404,'msg'=>"插入失败"]);
        }

    }
    public  function delete(){

        $method=$this->request->method();
        if($method !='POST'){
            return json(['code'=>404,'msg'=>"插入失败"]);
        }
        $data1=input('post.');
        $validata=validate('Nav');

        if(! $validata->scene('del')->check($data1)){
            return json(['code'=>404,'msg'=>$validata->getError()]);
        };



        $id=input('post.id');
        $data=Db::table('nav')->where('id',$id)->delete();
        if($data>0){
            return json(['code'=>200,'msg'=>"删除成功"]);
        }else{
            return json(['code'=>404,'msg'=>"删除失败"]);
        }
    }
    public function update(){
        $method=$this->request->method();
        if($method !='POST'){
            return json(['code'=>404,'msg'=>"插入失败"]);
        }
        $data1=input('post.');
        $validata=validate('Nav');

        if(! $validata->scene('update')->check($data1)){
            return json(['code'=>404,'msg'=>$validata->getError()]);
        };

        $id=input('post.id');

        $value=input('post.value');
        $field=input('post.field');

        $data=Db::table('nav')->where('id',$id)->update([$field=>$value]);
        if($data>0){
            return json(['code'=>200,'msg'=>"修改成功"]);
        }else{
            return json(['code'=>404,'msg'=>"修改失败"]);
        }
    }

    public function query(){
      $data=  Db::table('nav')->select();
      $count=Db::table('nav')->count();
    return json([
           'code'=>0,
           'msg'=>'success',
           'data'=>$data,
           'count'=>$count
       ]);
    }
}